### ISSUE TITLE
AppImage support?

### ISSUE THREAD

**Issue by samrocketman** [gimp-ci/docker-jenkins-gimp#3]
Someone mentioned it could be useful to check out.

**Comment by samrocketman** [comment]
https://github.com/aferrero2707/gimp-appimage by @aferrero2707 is worth checking out and incorporating when ready for this.

**Comment by aferrero2707** [comment]
@samrocketman please take into account the following aspects related to the GIMP AppImage:
* the build system uses a custom Docker container that is based on Ubuntu 14.04, and is designed to run on Travis-CI
* the AppImage has to be built on the "oldest system that works", in order to allow for compatibility with as many linux systems as possible

**Comment by samrocketman** [comment]
Thanks for the notes.  I was reviewing your source and noticed that.  I don’t think that’s a big deal.

At the moment it looks like it is only building for GIMP 2.10 branch.  When building it on build.gimp.org it makes sense to build 2.10 and master.

**Comment by aferrero2707** [comment]
I am planning to add support for building AppImages for the master branch, but for that I need to use a different Docker container that provides the GTK+3 libraries.

What are the advantages of using build.gimp.org instead of Travis-CI? I am asking for two main reasons:
* Travis is free of charge for open-source projects, it works well, it does not require maintenance from our side, and is nicely integrated with github
* it provides MacOS virtual machines, so MacOS packages can be created as well (see [here](https://github.com/aferrero2707/gimp-osx))

**Comment by samrocketman** [comment]
The main case for not using Travis CI is lack of integration with SCM hosting that is not GitHub.

There’s a few core requirements from the maintainers I must satisfy when choosing a CI service.

* The CI code must not live with the projects (BABL, GEGL, GIMP, etc).  I asked if it could and this is not desirable at this time.
* The code must be hosted with GNOME project Git servers.  Before they were using a basic Git service but are currently in the process of migrating to gitlab.gnome.org.

Because of the two requirements above Travis CI is not an option (I do use it for my GitHub hosted personal projects and am extremely familiar with its advanced features).

I have a few additional personal requirements.

- changes to build.gimp.org must be publicly auditable.
- anybody should be able to create a copy of build.gimp.org and run it for themselves locally.
- the CI process should be transparent and public (as code and written documentation).

**Comment by samrocketman** [comment]
Note none of the above requirements say use Jenkins.  So if there’s a better alternative I’m always open to it.  I inherited build.gimp.org and it was already Jenkins.  I also have a ton of professional experience with Jenkins and am a contributor to the OSS project.

Again I’m always open to checking out new things if they make sense and I don’t have to compromise on any of the above requirements.

**Comment by schumaml** [comment]
Travis-CI is not a requirement, it does not matter how you build the binaries, actually - just that they get built. This is a question I asked during the chat with probono on the #gimp IRC channel.

So an approach like we are doing it right now for the build.gimp.org containers, but with a slightly different build setup would work - a much older distro to keep compatibility with older system libraries, and due to the higher number of complex dependencies, a  jhbuild-based build. 

Most of this is already in place in the files made by aferrero2707, what I'd like to have is a meeting on IRC to go through the various files and check what does what, and why.

**Comment by aferrero2707** [comment]
> Most of this is already in place in the files made by aferrero2707, what I'd like to have is a meeting on IRC to go through the various files and check what does what, and why.

From my side I have no objection about using a different CI infrastructure - as long as the migration is not too complicated.

The OSX case is a bit different I guess, unless gimp.build.org also provides MacOS VMs. I have seen on G+ people complaining about the missing OSX packages for 2.10.2, and I'd like to help on that as well if possible.

I am available for chatting on IRC, and I think it is a good idea, but not before the beginning of next week. Maybe Monday evening CET?

**Comment by samrocketman** [comment]
I'm open to connecting an OSX agent to build.gimp.org.  At this time, I do not have an agent to connect.  I do have a Mac but it's not my personal equipment and belongs to my company.  So that wouldn't be a good agent in my opinion considering the amount of monitoring software on it (and it not being my own property).

**Comment by aferrero2707** [comment]
> I'm open to connecting an OSX agent to build.gimp.org.

What is cool about the Travis-CI OSX environment is that it is based on single-use virtual machines. Apart from the obvious security advantages, this also allows to fiddle with the system without any risk of breaking things (at worst, the job fails...). I would not be comfortable with using a real physical system that I might break...

Unfortunately there are no MacOS Docker containers!

**Comment by samrocketman** [comment]
There is a VirtualBox plugin in Jenkins which can be updated.  Mac OS X EULA allows up to two VirtualMachines of MacOS to be running on a physical Mac.  Hooking up a Mac agent does not have to mean it is a permanent agent.

Now that we’re using pipeline as code we can even manage vbox without the outdated Jenkins plugin.

Example: after each build a Virtualbox snapshot is rolled back.

To be clear: a real Mac is required to legally run Mac OS X even in a virtualized environment.  There’s no getting around that.

**Comment by aferrero2707** [comment]
Cool! Then this is probably even better than Travis, as we could pre-install most of the dependencies for GIMP. Currently in my jobs I am uploading a tar archive of the homebrew folder in order to provide a cached version of most of the dependencies. But that's just a workaround...

**Comment by samrocketman** [comment]
# DEPRECATED

This project has been migrated to [GNOME GitLab under World/gimp-ci](https://gitlab.gnome.org/World/gimp-ci).  Refer to [the documentation repository for better information](https://gitlab.gnome.org/World/gimp-ci/documentation).  If you just want to build GIMP, then [check out the GIMP development environment based on Docker](https://gitlab.gnome.org/World/gimp-ci/docker-gimp).  The Docker environment also allows you to run GIMP if you have Xorg display; instructions therein.
